### ISSUE TITLE
Found a Bug

### ISSUE THREAD

**Issue by Shinygati** [nowrep/vita-shellbat#1]
Using R2 and even R3 there is a bug on my vita 1000 where the percentage will only go up to 89% when the battery is fully charged, i've tried disabling other plugins and restarting and that doesn't seem to help but the vita stops charging once it reaches 89% so i know it must be a problem with the plugin.

**Comment by nowrep** [comment]
If the time is correct (eg. it udpates it correctly) then there is no problem with the plugin.
It only uses `scePowerGetBatteryLifePercent()` (as all other battery plugins) to get battery percent, so if it reports incorrect value, you should file bug with Sony :D

**Comment by Shinygati** [comment]
I see.. so i guess this really is a sony bug then, anyway i'm not complaining it's still pretty accurate for what it does and better than nothing so i'm happy with it but just figured i'd report it anyway. :)

**Comment by nowrep** [comment]
You can check with other apps/plugins that shows battery percent, but if it shows the same value then I guess there is nothing to do about it.

**Comment by Shinygati** [comment]
Actually, just now right after waking up my vita from sleep mode it's now sitting at 95% so i might do some testing to see if it happens again and whether or not it's the same with other plugins like you mentioned.
