### ISSUE TITLE
These offsets are identical to 3.67/3.68's 

### ISSUE THREAD

**Issue by LiEnby** [nowrep/vita-shellbat#14]
https://github.com/nowrep/vita-shellbat/blob/27ca685b76d13a3bdaff3c6d1778ec55b1a81220/main.c#L189
https://github.com/nowrep/vita-shellbat/blob/27ca685b76d13a3bdaff3c6d1778ec55b1a81220/main.c#L190

why have a special case for 3.65 at all ?

**Comment by nowrep** [comment]
Yeah, you are right. It doesn't matter though.
